# Generated by Django 4.2 on 2023-04-17 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='reward_prize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='submission',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hackapp.user'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='bg_img',
            field=models.ImageField(null=True, upload_to='bg_images/'),
        ),
    ]
