# Generated by Django 4.2 on 2023-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_hackathon_created_hackathon_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_datetime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_datetime',
            field=models.TextField(null=True),
        ),
    ]
